/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePipeDTO
 */
export interface CreatePipeDTO {
    /**
     * 
     * @type {string}
     * @memberof CreatePipeDTO
     */
    pipelineData: string;
    /**
     * User who uploaded the image
     * @type {string}
     * @memberof CreatePipeDTO
     */
    uploadedBy: string;
}

/**
 * Check if a given object implements the CreatePipeDTO interface.
 */
export function instanceOfCreatePipeDTO(value: object): value is CreatePipeDTO {
    if (!('pipelineData' in value) || value['pipelineData'] === undefined) return false;
    if (!('uploadedBy' in value) || value['uploadedBy'] === undefined) return false;
    return true;
}

export function CreatePipeDTOFromJSON(json: any): CreatePipeDTO {
    return CreatePipeDTOFromJSONTyped(json, false);
}

export function CreatePipeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePipeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'pipelineData': json['pipelineData'],
        'uploadedBy': json['uploaded_by'],
    };
}

export function CreatePipeDTOToJSON(json: any): CreatePipeDTO {
    return CreatePipeDTOToJSONTyped(json, false);
}

export function CreatePipeDTOToJSONTyped(value?: CreatePipeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pipelineData': value['pipelineData'],
        'uploaded_by': value['uploadedBy'],
    };
}

