/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateImageDTO
 */
export interface CreateImageDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateImageDTO
     */
    imageData: string;
    /**
     * User who uploaded the image
     * @type {string}
     * @memberof CreateImageDTO
     */
    uploadedBy: string;
}

/**
 * Check if a given object implements the CreateImageDTO interface.
 */
export function instanceOfCreateImageDTO(value: object): value is CreateImageDTO {
    if (!('imageData' in value) || value['imageData'] === undefined) return false;
    if (!('uploadedBy' in value) || value['uploadedBy'] === undefined) return false;
    return true;
}

export function CreateImageDTOFromJSON(json: any): CreateImageDTO {
    return CreateImageDTOFromJSONTyped(json, false);
}

export function CreateImageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateImageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'imageData': json['imageData'],
        'uploadedBy': json['uploaded_by'],
    };
}

export function CreateImageDTOToJSON(json: any): CreateImageDTO {
    return CreateImageDTOToJSONTyped(json, false);
}

export function CreateImageDTOToJSONTyped(value?: CreateImageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageData': value['imageData'],
        'uploaded_by': value['uploadedBy'],
    };
}

