/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePostDTO
 */
export interface CreatePostDTO {
    /**
     * username of the user
     * @type {string}
     * @memberof CreatePostDTO
     */
    username: string;
    /**
     * description of the post
     * @type {string}
     * @memberof CreatePostDTO
     */
    description: string;
    /**
     * id of the image after using the pipeline
     * @type {number}
     * @memberof CreatePostDTO
     */
    resultImageId: number;
    /**
     * id of the image before using the pipeline
     * @type {number}
     * @memberof CreatePostDTO
     */
    originalImageId: number;
    /**
     * id of the pipeline
     * @type {number}
     * @memberof CreatePostDTO
     */
    pipelineId: number;
    /**
     * Visibility of the post: 0 - private, 1 - friends, 2 - public, 10x where x is group ID for specific groups
     * @type {number}
     * @memberof CreatePostDTO
     */
    visibility: number;
}

/**
 * Check if a given object implements the CreatePostDTO interface.
 */
export function instanceOfCreatePostDTO(value: object): value is CreatePostDTO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('resultImageId' in value) || value['resultImageId'] === undefined) return false;
    if (!('originalImageId' in value) || value['originalImageId'] === undefined) return false;
    if (!('pipelineId' in value) || value['pipelineId'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function CreatePostDTOFromJSON(json: any): CreatePostDTO {
    return CreatePostDTOFromJSONTyped(json, false);
}

export function CreatePostDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'description': json['description'],
        'resultImageId': json['result_image_id'],
        'originalImageId': json['original_image_id'],
        'pipelineId': json['pipeline_id'],
        'visibility': json['visibility'],
    };
}

export function CreatePostDTOToJSON(json: any): CreatePostDTO {
    return CreatePostDTOToJSONTyped(json, false);
}

export function CreatePostDTOToJSONTyped(value?: CreatePostDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'description': value['description'],
        'result_image_id': value['resultImageId'],
        'original_image_id': value['originalImageId'],
        'pipeline_id': value['pipelineId'],
        'visibility': value['visibility'],
    };
}

