/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * boolean response
 * @export
 * @interface InviteResponse
 */
export interface InviteResponse {
    /**
     * the response to the friendship invite
     * @type {boolean}
     * @memberof InviteResponse
     */
    acceptedInvite: boolean;
}

/**
 * Check if a given object implements the InviteResponse interface.
 */
export function instanceOfInviteResponse(value: object): value is InviteResponse {
    if (!('acceptedInvite' in value) || value['acceptedInvite'] === undefined) return false;
    return true;
}

export function InviteResponseFromJSON(json: any): InviteResponse {
    return InviteResponseFromJSONTyped(json, false);
}

export function InviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'acceptedInvite': json['acceptedInvite'],
    };
}

export function InviteResponseToJSON(json: any): InviteResponse {
    return InviteResponseToJSONTyped(json, false);
}

export function InviteResponseToJSONTyped(value?: InviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acceptedInvite': value['acceptedInvite'],
    };
}

