/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface PageUserDTO
 */
export interface PageUserDTO {
    /**
     * 
     * @type {number}
     * @memberof PageUserDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof PageUserDTO
     */
    content?: Array<UserDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageUserDTO
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageUserDTO
     */
    sort?: SortObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserDTO
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageUserDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageUserDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserDTO
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageUserDTO interface.
 */
export function instanceOfPageUserDTO(value: object): value is PageUserDTO {
    return true;
}

export function PageUserDTOFromJSON(json: any): PageUserDTO {
    return PageUserDTOFromJSONTyped(json, false);
}

export function PageUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserDTOFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageUserDTOToJSON(json: any): PageUserDTO {
    return PageUserDTOToJSONTyped(json, false);
}

export function PageUserDTOToJSONTyped(value?: PageUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserDTOToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

