/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * username of the user
     * @type {string}
     * @memberof UserDTO
     */
    username: string;
    /**
     * display name of the user
     * @type {string}
     * @memberof UserDTO
     */
    displayName: string;
    /**
     * email of the user
     * @type {string}
     * @memberof UserDTO
     */
    email: string;
    /**
     * date of creation of the user
     * @type {Date}
     * @memberof UserDTO
     */
    createdAt: Date;
    /**
     * role of the user
     * @type {string}
     * @memberof UserDTO
     */
    role: UserDTORoleEnum;
}


/**
 * @export
 */
export const UserDTORoleEnum = {
    User: 'USER',
    Admin: 'ADMIN',
    Manager: 'MANAGER'
} as const;
export type UserDTORoleEnum = typeof UserDTORoleEnum[keyof typeof UserDTORoleEnum];


/**
 * Check if a given object implements the UserDTO interface.
 */
export function instanceOfUserDTO(value: object): value is UserDTO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'displayName': json['display_name'],
        'email': json['email'],
        'createdAt': (new Date(json['created_at'])),
        'role': json['role'],
    };
}

export function UserDTOToJSON(json: any): UserDTO {
    return UserDTOToJSONTyped(json, false);
}

export function UserDTOToJSONTyped(value?: UserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'displayName': value['displayName'],
        'email': value['email'],
        'createdAt': ((value['createdAt']).toISOString()),
        'role': value['role'],
    };
}

