/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * updated data of the user
 * @export
 * @interface UserUpdateDTO
 */
export interface UserUpdateDTO {
    /**
     * username of the user
     * @type {string}
     * @memberof UserUpdateDTO
     */
    username: string;
    /**
     * display name of the user
     * @type {string}
     * @memberof UserUpdateDTO
     */
    displayName: string;
    /**
     * hash of the password using the bcrypt encoder
     * @type {string}
     * @memberof UserUpdateDTO
     */
    passwordHash: string;
    /**
     * email of the user
     * @type {string}
     * @memberof UserUpdateDTO
     */
    email: string;
}

/**
 * Check if a given object implements the UserUpdateDTO interface.
 */
export function instanceOfUserUpdateDTO(value: object): value is UserUpdateDTO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('passwordHash' in value) || value['passwordHash'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserUpdateDTOFromJSON(json: any): UserUpdateDTO {
    return UserUpdateDTOFromJSONTyped(json, false);
}

export function UserUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'displayName': json['display_name'],
        'passwordHash': json['password_hash'],
        'email': json['email'],
    };
}

export function UserUpdateDTOToJSON(json: any): UserUpdateDTO {
    return UserUpdateDTOToJSONTyped(json, false);
}

export function UserUpdateDTOToJSONTyped(value?: UserUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'display_name': value['displayName'],
        'password_hash': value['passwordHash'],
        'email': value['email'],
    };
}

