/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * data of the user to be created
 * @export
 * @interface UserCreateDTO
 */
export interface UserCreateDTO {
    /**
     * username of the user
     * @type {string}
     * @memberof UserCreateDTO
     */
    username: string;
    /**
     * display name of the user
     * @type {string}
     * @memberof UserCreateDTO
     */
    displayName: string;
    /**
     * hash of the password using the bcrypt encoder
     * @type {string}
     * @memberof UserCreateDTO
     */
    passwordHash: string;
    /**
     * email of the user
     * @type {string}
     * @memberof UserCreateDTO
     */
    email: string;
    /**
     * role of the user
     * @type {string}
     * @memberof UserCreateDTO
     */
    role: UserCreateDTORoleEnum;
}


/**
 * @export
 */
export const UserCreateDTORoleEnum = {
    User: 'USER',
    Admin: 'ADMIN',
    Manager: 'MANAGER'
} as const;
export type UserCreateDTORoleEnum = typeof UserCreateDTORoleEnum[keyof typeof UserCreateDTORoleEnum];


/**
 * Check if a given object implements the UserCreateDTO interface.
 */
export function instanceOfUserCreateDTO(value: object): value is UserCreateDTO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('passwordHash' in value) || value['passwordHash'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserCreateDTOFromJSON(json: any): UserCreateDTO {
    return UserCreateDTOFromJSONTyped(json, false);
}

export function UserCreateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'displayName': json['display_name'],
        'passwordHash': json['password_hash'],
        'email': json['email'],
        'role': json['role'],
    };
}

export function UserCreateDTOToJSON(json: any): UserCreateDTO {
    return UserCreateDTOToJSONTyped(json, false);
}

export function UserCreateDTOToJSONTyped(value?: UserCreateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'display_name': value['displayName'],
        'password_hash': value['passwordHash'],
        'email': value['email'],
        'role': value['role'],
    };
}

